---
  - hosts: "all"
    become: yes
    tasks:

     - name: Copy vraper file
       ansible.builtin.copy:
          src: ./vraper.sh
          dest: /tmp
          owner: root
          group: root
          mode: '0755'

     - name: stop firewalld if exist
       shell: /tmp/vraper.sh

     - name: "open ports"
       ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - "22"
          - "80"
          - "443"
        jump: ACCEPT

     - name: Allow connections, if established
       ansible.builtin.iptables:
         chain: INPUT
         ctstate: ESTABLISHED,RELATED
         jump: ACCEPT
       become: yes

     - name: Set INPUT policy to DROP
       ansible.builtin.iptables:
         chain: INPUT
         policy: DROP
